### ISSUE TITLE
ADB "This App can not run on your PC"

### ISSUE THREAD

**Issue by Flo2304** [Simizfo/WSATools#21]
If i install from WSATools, i get the prompt for installing adb, then choose a location, get through everything and stuck at installing apk. After restart, i get the "This app can not run on your PC" message. If i install adb from "platform tools", WSATools is stuck loading the install app screen. 

For clarification, i'm running Windows 11 Pro 64bit, with Ryzen 5 3600

**Comment by Simizfo** [comment]
This is really strange.

I'll have a new version out soon, by the way, which fixes the platform-tools incompatibility and some more issues related to adb. Leaving this open for now.

**Comment by AmitKKhanchandani** [comment]
> If i install from WSATools, i get the prompt for installing adb, then choose a location, get through everything and stuck at installing apk. After restart, i get the "This app can not run on your PC" message. If i install adb from "platform tools", WSATools is stuck loading the install app screen.
> 
> For clarification, i'm running Windows 11 Pro 64bit, with Ryzen 5 3600

Same happening with me as well.

**Comment by Simizfo** [comment]
Thanks for reporting. Please try when the next version gets released soon.

**Comment by Sir0ne** [comment]
> If i install from WSATools, i get the prompt for installing adb, then choose a location, get through everything and stuck at installing apk. After restart, i get the "This app can not run on your PC" message. If i install adb from "platform tools", WSATools is stuck loading the install app screen.
> 
> For clarification, i'm running Windows 11 Pro 64bit, with Ryzen 5 3600

have you tried not opening directly into the folder but selecting the folder than opening the abd file

**Comment by archon810** [comment]
Getting the same error with 0.1.70.0 installed from the Windows Store on today's stable Windows 11 update that enabled the Android subsystem and the Amazon Appstore. I'm on a Lenovo ThinkPad X1 with Intel Core i7-1185G7.

https://twitter.com/ArtemR/status/1493697788374228993

**Comment by Silvenga** [comment]
Same issue, it's kind of odd though:

I'm using the `file` tool from GNU (commonly installed on Linux).

The ADB tool downloaded by WSATool:

```bash
file adb.exe
adb.exe; PE32 executable for MS Windows (console) Intel 80386 32-bit
```

This should definitely run. Running adb directly:

```powershell
PS E:\Programs\WSATools\adb> .\adb.exe
Program 'adb.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ .\adb.exe
+ ~~~~~~~~~.
At line:1 char:1
+ .\adb.exe
+ ~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

So I downloaded ADB manually and replaced the WSATool downloaded version, running `file` again:

```bash
file adb.exe
adb.exe; PE32 executable for MS Windows (console) Intel 80386 32-bit
```

```powershell
.\adb.exe help
Android Debug Bridge version 1.0.41
Version 32.0.0-8006631
Installed as E:\Programs\WSATools\adb\adb.exe
...
```

Now I try and install a APK, and WSATool just keeps "Loading".

Something is screwy.

**Comment by archon810** [comment]
This is exactly what I did and exactly what happened to me as well. Ended up switching to https://github.com/alesimula/wsa_pacman/ which looks like a more polished and robust solution (sorry).

**Comment by Simizfo** [comment]
Well, legit, I guess. If my app doesn't work, you'll look for another one :D 
I'm back working on the app, so I'll see what I can do about this.

**Comment by GreakFreak** [comment]
I am also having the same issue.

Based on this thread, I took a shot downloading WSA Pacman and am able to succesfully download APKs with no issues.

I hope this issue is resolved so that I can redownload and support a developer that uses the MS Store. Happy to help with recreating the issue or anything else that may help you.

**Comment by Simizfo** [comment]
Just wanted to note that WSA Pacman and any other tools that ship bundled platform-tools or any part of it (like ADB) are going against its [Terms and Conditions (click on any download link to see them)](https://developer.android.com/studio/releases/platform-tools), precisely part 3. WSATools fully respects Google/Alphabet's Terms and Conditions for the end user too, by downloading the package on the user behalf at runtime. Also, the Microsoft Store wouldn't allow me to redistribute adb inside it.

That being said. Something might have changed on Google/Alphabet's side, and WSATools just isn't able to prepare it for usage. I'll have a look as soon as tomorrow, since I'll start working full time on the app again. Thanks, @GreakFreak, btw!

I'll let everyone here know, in case I need help to troubleshoot this.

**Comment by Silvenga** [comment]
FWIW, ADB source is under the Apache 2.0 license (https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), which allows distribution. One could argue that the code compiled from this source is equally under Apache. Even if not, then building ADB and including that compile version would be under Apache (then it get's interesting if both of those files matched).

I remember years ago when Oracle gave a tech talk and the Oracle developers had a lawyer following them at all times. Many things Google does is purely because a lawyer requested it. Given that wsa_pacman is an OSS project (GNU license), Google would never go after them for such a questionable problem, it would be insane.

**Comment by towo** [comment]
Downgrade to [31.0.3](https://dl.google.com/android/repository/platform-tools_r31.0.3-windows.zip) and you're good, it just seems to be an issue with version 32.0.0 of the platform tools / ADB.

**Comment by Simizfo** [comment]
Nope, sorry. This works with 32.0.0 of platform tools as well, if you download it manually. 

So, here's what's happening: the issue is that Windows apparently started recently to mark ADB downloaded by WSATools as malicious. The SmartScreen popup never used to appear, before. It definitely is a false positive. After all, it's platform-tools downloaded from Google. You can check yourself if you run a network tool like Fiddler that my app downloads a legit copy of platform-tools.

I've contacted Microsoft to have this solved 👍

**Comment by Simizfo** [comment]
Anyone here, can you please try WSATools again and see if it works now? You shouldn't need any update, or maybe you just need to have Windows Defender definitions updated from Windows Update.

@towo  @Flo2304  @AmitKKhanchandani @Silvenga

**Comment by AmitKKhanchandani** [comment]
Let me try and update here.

**Comment by Simizfo** [comment]
This is solved. 

SmartScreen mistakenly reported the new ADB version as unsafe, and made it unusable. Microsoft has fixed this and now WSATools works fine as it used to do.

Thanks everyone who reported this!
