### ISSUE TITLE
Feature Proposal: Add the ability to point to a custom ADB location

### ISSUE THREAD

**Issue by jamesmcroft** [Simizfo/WSATools#28]
It doesn't seem possible to bypass the dialog to install ADB when it is already installed. 

Is there a way to configure this in settings to point to the install location? Is WSATools expecting ADB to be in a specific location?

**Comment by Simizfo** [comment]
No, WSATools doesn't expect it to be in a specific location. 

The current version looks for it if it's present in the path system environment variable. If it doesn't find it there, it asks to install it manually. 

That being said, there was some case where ADB wasn't detected correctly in both of those cases, and it triggered this bug. It should be fixed in the next version, as I have rewritten the code to check for ADB 👍 

But having a way to point a custom ADB location is a good idea, yeah 🤔 Marking this as improvement, will look into it!

Thanks!

**Comment by Simizfo** [comment]
The bug should be fixed in 0.1.80 which just got released. Changing the title to fit the feature suggestion you've made. Thanks!

**Comment by jamesmcroft** [comment]
Thanks for the update @Simizfo 👍🏻

**Comment by Simizfo** [comment]
Thank you for taking your time for this! ❤️

**Comment by Simizfo** [comment]
This feature is ready and will come in the next update. Will close this issue once it's out. Thank you!
