### ISSUE TITLE
Cannot login to any apps

### ISSUE THREAD

**Issue by mareekkk** [Simizfo/WSATools#68]
Installed successfully. No error. USB Debugging enabled. All firewalls off and no VPNs active. Trying to login to any app does not do anything. There is a 2 second loading but nothing happens after that, there is no error as well. App stays on login screen.

**Comment by Simizfo** [comment]
Hi there. WSATools is an app that installs Android apps into Windows Subsystem for Android. Windows Subsystem for Android (which is made by Microsoft) does actually run and manage your app (its connection, files, and everything after WSATools installs it).

So... sorry about it, but there's nothing I can do about this issue!

I'll close this since it's out of the app scope.
