### ISSUE TITLE
What about internet connection and hardware sharing with windows ?

### ISSUE THREAD

**Issue by Poneyrules** [Simizfo/WSATools#72]
Hello, 

I have a stupid question about internet connexion of the intalled apps, it's working ?
I tryin to use CIVTak with WSAtools and i can't connect it on internet for online map download.

In the app i can see my ip adresse and it's 169.x.x.x so i think the app have no access to my network card (ethernet).
There is sharring of my hardware devices between windows and WSAtools ? like with VMware or something like this 

Thank you for your time.

regards

**Comment by Simizfo** [comment]
Hi there. WSATools is an app that installs Android apps into Windows Subsystem for Android. Windows Subsystem for Android (which is made by Microsoft) does actually run and manage your app (its connection, files, and everything after WSATools installs it).

So... sorry about it, but there's nothing I can do about this issue!

I'll close this since it's out of the app scope.
